### ISSUE TITLE
How to avoid steam redownloading

### ISSUE THREAD

**Issue by ajventer** [Omni-guides/Wabbajack-Linux-Bottles#2]
>Once steam is opened, click Skyrim Special Edition, and click install. For reasons I have yet to work out, even though Steam will detect the game and say it is discovering files, it will still ultimately want to redownload the whole game... At least it's not doubling up on space used with this method, but a little annoying. If you work out how to avoid this, let me know ;)

I know the answer, so I'm doing as you asked. Steam does NOT only look at the install dir to know what is installed, it looks at the appmanifest file FIRST. In order to prevent a redownload you need the game files present in steamapps/common/${GAME NAME} - which your guide already includes, but you ALSO need the appmanifest file present in steamapps directly. This would be called something like appmanifest_${GAMEID}.acf - if both files are present, steam will recognize the game as fully installed and use it without a reinstall.

**Comment by Omni-guides** [comment]
Thanks, this makes sense indeed. (Apologies for the delayed response, I was on vacation).

I'll see if I can work out a simple way to lay that out in the guide, although I'm not sure how effective the guide is now, given that it's locked at an older version of Wabbajack until I can work out how to get EdgeView to behave properly under wine, for the nexus login..

**Comment by ajventer** [comment]
Yeah I still have to use it from Windows, and some modlists break the VFS
in MO2 under wine, no idea why/how.

Specifically Licentia-Black I've had that issue, and couldn't fix it,
journey is working great though.

So I think we are going to have a year or two of struggling before we have
a consistent, smooth modding experience under Linux.

I suppose one could install vortex and use Nexus collections but they are
not nearly as automated and have zero automaton for other sites.

**Comment by Omni-guides** [comment]
With the main WJ dev moving to Nexus to work on Vortex, who knows what we will see in future. I don't see Nexus Collections as a replacement for WJ lists though...

It's a shame you see VFS issues with that list - I haven't really come up against a list so far that has that issue - some have mods that are just flat out incompatible, but that's usually at the mod level, rather than the MO2 level. If I get time, maybe I'll see if I can work something out for Licentia-Black.

**Comment by ajventer** [comment]
Cool, thanks!

I have no idea what triggers it. I agree collections aren't a replacement,
perhaps eventually they will be but that's not where we are now.
